id: arcgis_zoning_tod
source_type: arcgis
target_table: zoning_overlays
jurisdiction_id: austin-tx
base_url: https://maps.austintexas.gov/arcgis/rest/services/Shared/Zoning_2/MapServer
dataset_id: ""
license: Public Domain
refresh_cadence: monthly
filters:
  where: "1=1"
  outFields: "STATION_NAME,STATION_TYPE,TOD_SUB_DISTRICT"
layers:
  - id: 26
    name: "Transit Oriented Development"
field_map:
  - raw_field: STATION_NAME
    template: "{STATION_NAME} - {TOD_SUB_DISTRICT}"
    schema_field: overlay_name
    type: text
    required: true
  - raw_field: STATION_TYPE
    schema_field: overlay_type
    type: text
  - raw_field: _layer_name
    schema_field: layer_name
    type: text
  - raw_field: _layer_id
    schema_field: layer_id
    type: integer
  - raw_field: _geometry_wkt
    schema_field: geometry_wkt
    type: text
