id: arcgis_travis_flood_zone
source_type: arcgis
target_table: environmental_constraints
jurisdiction_id: austin-tx
base_url: https://services1.arcgis.com/0L95CJ0VTaxqcmED/arcgis/rest/services/Travis_County_Flood_Zone_Map_WFL1/FeatureServer
dataset_id: ""
license: Public Domain
refresh_cadence: monthly
filters:
  where: "1=1"
  outFields: "*"
layers:
  - id: 0
    name: "FEMA Flood Zone"
field_map:
  - raw_field: FLD_ZONE
    schema_field: name
    type: text
  - raw_field: ZONE_SUBTY
    schema_field: description
    type: text
  - raw_field: _geometry_wkt
    schema_field: geometry_wkt
    type: text
