id: arcgis_water_service
source_type: arcgis
target_table: utility_capacity
jurisdiction_id: austin-tx
base_url: https://maps.austintexas.gov/arcgis/rest/services/AustinWater/MapServer
dataset_id: ""
license: Public Domain
refresh_cadence: monthly
filters:
  where: "1=1"
  outFields: "*"
layers:
  - id: 0
    name: "Water Service Area"
field_map:
  - raw_field: NAME
    schema_field: facility_name
    type: text
  - raw_field: _layer_name
    schema_field: metric_name
    type: text
  - raw_field: _geometry_wkt
    schema_field: geometry_wkt
    type: text
