id: arcgis_transit_bus_stops
source_type: arcgis
target_table: transit_amenities
jurisdiction_id: austin-tx
base_url: https://maps.austintexas.gov/arcgis/rest/services/Shared/Transportation_1/MapServer
dataset_id: ""
license: Public Domain
refresh_cadence: weekly
external_id_template: "{STOP_ID}"
filters:
  where: "1=1"
  outFields: "STOP_ID,STOP_NAME,ON_STREET,AT_STREET,STOP_TYPE,LATITUDE,LONGITUDE"
layers:
  - id: 3
    name: "Capital Metro Bus Stops"
field_map:
  - raw_field: STOP_ID
    schema_field: stop_id
    type: text
    required: true
  - raw_field: STOP_NAME
    schema_field: name
    type: text
  - raw_field: ON_STREET
    schema_field: address
    type: text
  - raw_field: STOP_TYPE
    schema_field: route_type
    type: text
  - raw_field: LATITUDE
    schema_field: latitude
    type: float
  - raw_field: LONGITUDE
    schema_field: longitude
    type: float
  - raw_field: _geometry_wkt
    schema_field: geometry_wkt
    type: text
