id: arcgis_zoning_infill_extended
source_type: arcgis
target_table: zoning_overlays
jurisdiction_id: austin-tx
base_url: https://maps.austintexas.gov/arcgis/rest/services/Shared/Zoning_4/MapServer
dataset_id: ""
license: Public Domain
refresh_cadence: weekly
filters:
  where: "1=1"
  outFields: "*"
layers:
  - id: 8
    name: "Parking Placement Design Option"
  - id: 9
    name: "Front Porch Design Option"
  - id: 10
    name: "Garage Placement Design Option"
field_map:
  - raw_field: COMMENTS
    schema_field: overlay_name
    type: text
  - raw_field: _layer_name
    schema_field: overlay_type
    type: text
  - raw_field: _layer_name
    schema_field: layer_name
    type: text
  - raw_field: _layer_id
    schema_field: layer_id
    type: integer
  - raw_field: _geometry_wkt
    schema_field: geometry_wkt
    type: text
