id: arcgis_council_districts
source_type: arcgis
target_table: zoning_overlays
jurisdiction_id: austin-tx
base_url: https://maps.austintexas.gov/arcgis/rest/services/Shared/Property/MapServer
dataset_id: ""
license: Public Domain
refresh_cadence: annually
filters:
  where: "1=1"
  outFields: "COUNCIL_DISTRICT"
layers:
  - id: 3
    name: "Council Districts"
field_map:
  - raw_field: COUNCIL_DISTRICT
    schema_field: overlay_name
    type: text
    required: true
  - raw_field: _layer_name
    schema_field: overlay_type
    type: text
  - raw_field: _layer_name
    schema_field: layer_name
    type: text
  - raw_field: _layer_id
    schema_field: layer_id
    type: integer
  - raw_field: _geometry_wkt
    schema_field: geometry_wkt
    type: text
