id: arcgis_city_owned_land
source_type: arcgis
target_table: environmental_constraints
jurisdiction_id: austin-tx
base_url: https://maps.austintexas.gov/arcgis/rest/services/Shared/Infrastructure_2/MapServer
dataset_id: ""
license: Public Domain
refresh_cadence: monthly
filters:
  where: "1=1"
  outFields: "CITY_OF_AUSTIN_PARCELS_ID,DOCUMENT_TYPE"
layers:
  - id: 3
    name: "City of Austin Owned Parcels"
field_map:
  - raw_field: CITY_OF_AUSTIN_PARCELS_ID
    schema_field: name
    type: text
    required: true
  - raw_field: DOCUMENT_TYPE
    schema_field: description
    type: text
  - raw_field: _geometry_wkt
    schema_field: geometry_wkt
    type: text
