id: austin_brownfields
source_type: socrata
target_table: environmental_constraints
jurisdiction_id: austin-tx
base_url: https://data.austintexas.gov
dataset_id: 22wq-47zy
license: Public Domain
refresh_cadence: as_needed
filters: {}
field_map:
  - raw_field: site_identification
    schema_field: name
    type: text
    required: true
  - raw_field: proposed_redevelopment
    schema_field: description
    type: text
  - raw_field: status
    schema_field: severity
    type: text
